require: rubocop-performance
require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
